config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    #collection is where we put routes that do not
    #pertain to individual posts
    #GET /posts/archives
    #collection do
    #  get :archives
    #end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
   # resources :votes, only: [:create]  # this would do a /posts/:id/votes => votes#create
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :edit, :show, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  has_many :votes, as: :voteable

  validates :comment, presence: true

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_id]
    #@comment = Comment.new(params.require(:comment).permit(:comment))
    #@comment.post = @post
    @comment = @post.comments.build(params.require(:comment).permit(:comment)) #this line replace the above two
    @comment.creator = current_user#User.first #need to fix this after authentication

    if @comment.save
      flash[:notice] = 'Your comment was added.'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    require_user
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote once."
        end
        redirect_to :back #wherever you came from...
      end
      format.js
    end
  end
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do  %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>
    <span id='comment_<%=comment.id%>_votes'><%= comment.total_votes %></span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' , remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class="well span8"</div>
    <em>"<%= comment.comment %>"</em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class='quiet'>by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
    <small>at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%=@comment.id%>_votes').html('<%=@comment.total_votes%> votes');
<% else %>
  alert('You can only vote on a comment once.');
<% end %>