config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    #collection is where we put routes that do not
    #pertain to individual posts
    #GET /posts/archives
    #collection do
    #  get :archives
    #end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
   # resources :votes, only: [:create]  # this would do a /posts/:id/votes => votes#create
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :edit, :show, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  #before_save :generate_slug! #see active record callbacks.

  sluggable_column :title


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # purpose of before_action:
  # 1. set up something
  # 2. redirect away from action
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new

=begin
 #playing around with exposing API, working along with the lecture.
    respond_to do |format|
      format.html
      format.json { render json: @post }
      format.xml { render xml: @post }
    end
=end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user  #User.first #TODO: change once we have authentication... this is just
                               #to make sure our post does not have a nil foreign key for
                               #the user.

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit; end

  def update
    if @post.update(post_params)      #mass assignment
      flash[:notice] = "The post was updated."
      redirect_to post_path
    else
      render :edit
    end
  end

  def vote
    require_user
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:notice] = "You can only vote on a post once."
        end
        redirect_to :back #wherever you came from...
        #The redirect has to go here... after the format.js is no good because you can render
        #or redirect, but you can't do both.
      end

      format.js  # the default is that rails will try to render a template by the same name
                 # as the action.  In this case, it would be vote.js.erb in the post controller.
    end
  end

private

#strong parameters to expose the fields we want
#to mass assign
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])  #notice special syntax for virtual attribute that is an array
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
  <% if @post.errors.any? %>
    <%= render 'shared/errors', obj: @post %>
  <% end %>

<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
    <p/>
    <br/>
    <%= f.submit(@post.new_record? ? "Create Post" : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<div class="row">
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>
    <span id='post_<%=post.slug%>_votes'><%= post.total_votes %></span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>Posted by </span><%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h4>Edit A Post</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'posts', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create A New Post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? and current_user == @post.creator || current_user.admin? %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post)%>]
  </p>
<% end %>
<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class='control-group'>
    	<%= f.label :comment, "Leave a comment" %>
   	<%= f.text_area :comment, rows: 5, class: 'span4'   %>
    </div>
    <%= f.submit("Create Comment", class: 'btn btn-primary') %>
  <% end %>
<% end %>

<h5>Comments:</h5>

<!-- reload.. on validation error, we have a comment that is not saved in the datebase associated
with this post... and we are trying to render that particular comment.  By doing a reload, only the
saved comments are associated with this post.
-->
<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%=@post.slug%>_votes').html('<%=@post.total_votes%> votes');
<% else %>
  alert('You can only vote on a post once.');
<% end %>