config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    #collection is where we put routes that do not
    #pertain to individual posts
    #GET /posts/archives
    #collection do
    #  get :archives
    #end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
   # resources :votes, only: [:create]  # this would do a /posts/:id/votes => votes#create
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :edit, :show, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  sluggable_column :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_admin, only: [:new, :create]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created."
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = "The post was updated."
      redirect_to post_path
    else
      render :edit
    end
  end

  #strong parameters to expose the fields we want
  #to mass assign
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by slug: params[:id]
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <%= render 'shared/errors', obj: @category %>
<% end %>

<div class='well'>
  <%= form_for @category do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit(@category.new_record? ? "Create Category" : 'Update Category', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h4>Edit A Category</h4>

<%= render 'form' %>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: "All Categories" %>

<% @categories.each do |category| %>
  <div class="row">
    <!-- <div class='span8 well'> -->
    <ul>
    <li>
      <%= category.name %>
    </li>
    </ul>
    <!-- </div> -->
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>
<%= render 'form' %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; Showing Category: #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/posts', post: post %>
<% end %>